version: 2
jobs:
  flake8:
    docker:
      - image: python:2.7
    steps:
      - run: pip install flake8
      - checkout
      - run: flake8 .

  run_tests:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install .
      - command: python tests/test_match.py

workflows:
  version: 2
  jsonmatch:
    jobs:
      - flake8
      - run_tests:
        requires:
          - flake8
